# Generated by Django 6.0 on 2026-01-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reduce',
            field=models.BooleanField(default=False),
        ),
    ]
