# Generated by Django 6.0 on 2026-01-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stock_reduce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stock_reduce',
            new_name='stock_reduced',
        ),
    ]
